// <auto-generated />
namespace TechnicalSupportSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedVendorName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedVendorName));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191210122_addedVendorName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
