// <auto-generated />
namespace TechnicalSupportSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ComponentTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComponentTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191604276_ComponentTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
