// <auto-generated />
namespace TechnicalSupportSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedBoolSignupStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedBoolSignupStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201404111521093_addedBoolSignupStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
