// <auto-generated />
namespace TechnicalSupportSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedDeliveryCost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDeliveryCost));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191550244_addedDeliveryCost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
