// <auto-generated />
namespace TechnicalSupportSystemV2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated1));
        
        string IMigrationMetadata.Id
        {
            get { return "201311281902390_updated1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
